changes to compile regex into builds with mingw rerun autogensh
git-svn-id: https://crosswire.org/svn/sword/trunk@628 bcd7d363-81e1-0310-97ec-a550e20fc99c

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,5 +1,5 @@
 #! /bin/sh
-# From configure.ac Revision: 1.4 .
+# From configure.ac Revision: 1.6 .
 # Guess values for system-dependent variables and create Makefiles.
 # Generated by Autoconf 2.52 for sword 1.5.3.
 #
@@ -7705,6 +7705,15 @@ case "$target_os" in
     ;;
 esac
 
+case "$target_os" in
+  mingw*)
+    target_mingw32="yes"
+    ;;
+  *)
+    target_mingw32="no"
+    ;;
+esac
+
 # ---------------------------------------------------------------------
 # Substitute variables into makefiles
 # ---------------------------------------------------------------------
@@ -7713,7 +7722,7 @@ esac
 # Conditional variables
 # ---------------------------------------------------------------------
 
-if test x$target_os = xmingw32*; then
+if test x$target_mingw32 = xyes; then
   MINGW_TRUE=
   MINGW_FALSE='#'
 else
@@ -7839,7 +7848,7 @@ DEFS=-DHAVE_CONFIG_H
 : ${CONFIG_STATUS=./config.status}
 ac_clean_files_save=$ac_clean_files
 ac_clean_files="$ac_clean_files $CONFIG_STATUS"
-{ echo "$as_me:7842: creating $CONFIG_STATUS" >&5
+{ echo "$as_me:7851: creating $CONFIG_STATUS" >&5
 echo "$as_me: creating $CONFIG_STATUS" >&6;}
 cat >$CONFIG_STATUS <<_ACEOF
 #! $SHELL
@@ -8015,7 +8024,7 @@ cat >>$CONFIG_STATUS <<\EOF
     echo "$ac_cs_version"; exit 0 ;;
   --he | --h)
     # Conflict between --help and --header
-    { { echo "$as_me:8018: error: ambiguous option: $1
+    { { echo "$as_me:8027: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -8034,7 +8043,7 @@ Try \`$0 --help' for more information." >&2;}
     ac_need_defaults=false;;
 
   # This is an error.
-  -*) { { echo "$as_me:8037: error: unrecognized option: $1
+  -*) { { echo "$as_me:8046: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -8085,7 +8094,7 @@ do
   "utilities/Makefile" ) CONFIG_FILES="$CONFIG_FILES utilities/Makefile" ;;
   "default-1" ) CONFIG_COMMANDS="$CONFIG_COMMANDS default-1" ;;
   "config.h" ) CONFIG_HEADERS="$CONFIG_HEADERS config.h" ;;
-  *) { { echo "$as_me:8088: error: invalid argument: $ac_config_target" >&5
+  *) { { echo "$as_me:8097: error: invalid argument: $ac_config_target" >&5
 echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
    { (exit 1); exit 1; }; };;
   esac
@@ -8237,6 +8246,7 @@ s,@enable_vcl@,$enable_vcl,;t t
 s,@enable_debug@,$enable_debug,;t t
 s,@enable_profile@,$enable_profile,;t t
 s,@target_system@,$target_system,;t t
+s,@target_mingw32@,$target_mingw32,;t t
 s,@MINGW_TRUE@,$MINGW_TRUE,;t t
 s,@MINGW_FALSE@,$MINGW_FALSE,;t t
 s,@ICU_TRUE@,$ICU_TRUE,;t t
@@ -8361,7 +8371,7 @@ done; }
   esac
 
   if test x"$ac_file" != x-; then
-    { echo "$as_me:8364: creating $ac_file" >&5
+    { echo "$as_me:8374: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
     rm -f "$ac_file"
   fi
@@ -8379,7 +8389,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:8382: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:8392: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -8392,7 +8402,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:8395: error: cannot find input file: $f" >&5
+           { { echo "$as_me:8405: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -8453,7 +8463,7 @@ for ac_file in : $CONFIG_HEADERS; do test "x$ac_file" = x: && continue
   * )   ac_file_in=$ac_file.in ;;
   esac
 
-  test x"$ac_file" != x- && { echo "$as_me:8456: creating $ac_file" >&5
+  test x"$ac_file" != x- && { echo "$as_me:8466: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
 
   # First look for the input files in the build tree, otherwise in the
@@ -8464,7 +8474,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:8467: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:8477: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -8477,7 +8487,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:8480: error: cannot find input file: $f" >&5
+           { { echo "$as_me:8490: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -8594,7 +8604,7 @@ cat >>$CONFIG_STATUS <<\EOF
   rm -f $tmp/in
   if test x"$ac_file" != x-; then
     if cmp -s $ac_file $tmp/config.h 2>/dev/null; then
-      { echo "$as_me:8597: $ac_file is unchanged" >&5
+      { echo "$as_me:8607: $ac_file is unchanged" >&5
 echo "$as_me: $ac_file is unchanged" >&6;}
     else
       ac_dir=`$as_expr X"$ac_file" : 'X\(.*[^/]\)//*[^/][^/]*/*$' \| \
