Only set GLOBCONFPATH if sysconfdir is not /etc Create a sword.conf using your pkgdatadir (n.b. not recreated if exists already) don't install globals.conf if --without-conf is set rerun autogen.sh
git-svn-id: https://crosswire.org/svn/sword/trunk@626 bcd7d363-81e1-0310-97ec-a550e20fc99c

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,5 +1,5 @@
 #! /bin/sh
-# From configure.ac Revision: 1.3 .
+# From configure.ac Revision: 1.4 .
 # Guess values for system-dependent variables and create Makefiles.
 # Generated by Autoconf 2.52 for sword 1.5.3.
 #
@@ -7653,20 +7653,25 @@ if test x$enable_debug = xyes; then
   fi
   CFLAGS="$CFLAGS -Werror"
   CXXFLAGS="$CXXFLAGS -Werror"
-  cat >>confdefs.h <<\EOF
-#define DEBUG 1
-EOF
-
-else
-  cat >>confdefs.h <<\EOF
-#define NDEBUG 1
-EOF
-
 fi
+#  AC_DEFINE(DEBUG)
+#else
+#  AC_DEFINE(NDEBUG)
+#fi
 
 if test x$enable_profile = xyes; then
   CFLAGS="$CFLAGS -pg"
   CXXFLAGS="$CXXFLAGS -pg"
+fi
+
+# ---------------------------------------------------------------------
+# Alter global conf directory only if not /etc
+# ---------------------------------------------------------------------
+
+if test "x$sysconfdir" = "x/etc"; then
+  dir_confdef="no"
+else
+  dir_confdef="yes"
 fi
 
 # ---------------------------------------------------------------------
@@ -7738,6 +7743,14 @@ if test x$with_conf = xyes; then
 else
   INSTCONF_TRUE='#'
   INSTCONF_FALSE=
+fi
+
+if test x$dir_confdef = xyes; then
+  CONFDEF_TRUE=
+  CONFDEF_FALSE='#'
+else
+  CONFDEF_TRUE='#'
+  CONFDEF_FALSE=
 fi
 #AM_CONDITIONAL(DEBUG, test x$with_debug = xyes)
 #AM_CONDITIONAL(PROFILE, test x$with_profile = xyes)
@@ -7826,7 +7839,7 @@ DEFS=-DHAVE_CONFIG_H
 : ${CONFIG_STATUS=./config.status}
 ac_clean_files_save=$ac_clean_files
 ac_clean_files="$ac_clean_files $CONFIG_STATUS"
-{ echo "$as_me:7829: creating $CONFIG_STATUS" >&5
+{ echo "$as_me:7842: creating $CONFIG_STATUS" >&5
 echo "$as_me: creating $CONFIG_STATUS" >&6;}
 cat >$CONFIG_STATUS <<_ACEOF
 #! $SHELL
@@ -8002,7 +8015,7 @@ cat >>$CONFIG_STATUS <<\EOF
     echo "$ac_cs_version"; exit 0 ;;
   --he | --h)
     # Conflict between --help and --header
-    { { echo "$as_me:8005: error: ambiguous option: $1
+    { { echo "$as_me:8018: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -8021,7 +8034,7 @@ Try \`$0 --help' for more information." >&2;}
     ac_need_defaults=false;;
 
   # This is an error.
-  -*) { { echo "$as_me:8024: error: unrecognized option: $1
+  -*) { { echo "$as_me:8037: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -8072,7 +8085,7 @@ do
   "utilities/Makefile" ) CONFIG_FILES="$CONFIG_FILES utilities/Makefile" ;;
   "default-1" ) CONFIG_COMMANDS="$CONFIG_COMMANDS default-1" ;;
   "config.h" ) CONFIG_HEADERS="$CONFIG_HEADERS config.h" ;;
-  *) { { echo "$as_me:8075: error: invalid argument: $ac_config_target" >&5
+  *) { { echo "$as_me:8088: error: invalid argument: $ac_config_target" >&5
 echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
    { (exit 1); exit 1; }; };;
   esac
@@ -8219,6 +8232,7 @@ s,@MAINT@,$MAINT,;t t
 s,@with_zlib@,$with_zlib,;t t
 s,@with_icu@,$with_icu,;t t
 s,@with_conf@,$with_conf,;t t
+s,@dir_confdef@,$dir_confdef,;t t
 s,@enable_vcl@,$enable_vcl,;t t
 s,@enable_debug@,$enable_debug,;t t
 s,@enable_profile@,$enable_profile,;t t
@@ -8231,6 +8245,8 @@ s,@ZLIB_TRUE@,$ZLIB_TRUE,;t t
 s,@ZLIB_FALSE@,$ZLIB_FALSE,;t t
 s,@INSTCONF_TRUE@,$INSTCONF_TRUE,;t t
 s,@INSTCONF_FALSE@,$INSTCONF_FALSE,;t t
+s,@CONFDEF_TRUE@,$CONFDEF_TRUE,;t t
+s,@CONFDEF_FALSE@,$CONFDEF_FALSE,;t t
 CEOF
 
 EOF
@@ -8345,7 +8361,7 @@ done; }
   esac
 
   if test x"$ac_file" != x-; then
-    { echo "$as_me:8348: creating $ac_file" >&5
+    { echo "$as_me:8364: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
     rm -f "$ac_file"
   fi
@@ -8363,7 +8379,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:8366: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:8382: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -8376,7 +8392,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:8379: error: cannot find input file: $f" >&5
+           { { echo "$as_me:8395: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -8437,7 +8453,7 @@ for ac_file in : $CONFIG_HEADERS; do test "x$ac_file" = x: && continue
   * )   ac_file_in=$ac_file.in ;;
   esac
 
-  test x"$ac_file" != x- && { echo "$as_me:8440: creating $ac_file" >&5
+  test x"$ac_file" != x- && { echo "$as_me:8456: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
 
   # First look for the input files in the build tree, otherwise in the
@@ -8448,7 +8464,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:8451: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:8467: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -8461,7 +8477,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:8464: error: cannot find input file: $f" >&5
+           { { echo "$as_me:8480: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -8578,7 +8594,7 @@ cat >>$CONFIG_STATUS <<\EOF
   rm -f $tmp/in
   if test x"$ac_file" != x-; then
     if cmp -s $ac_file $tmp/config.h 2>/dev/null; then
-      { echo "$as_me:8581: $ac_file is unchanged" >&5
+      { echo "$as_me:8597: $ac_file is unchanged" >&5
 echo "$as_me: $ac_file is unchanged" >&6;}
     else
       ac_dir=`$as_expr X"$ac_file" : 'X\(.*[^/]\)//*[^/][^/]*/*$' \| \
